repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: detect-private-key

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--line-length=79"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: alembic/ # можем позже добавить необходимые папки для исключения
        args: ["--profile", "black", "--line-length=79"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: alembic/|__init__.py|init_db.py|endpoints/user.py # можем позже добавить необходимые папки для исключения
        additional_dependencies:
          - flake8-fastapi
          - flake8-comments
          - flake8-docstrings
          - flake8-broken-line
          - flake8-simplify
          - pep8-naming

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: alembic/ # можем позже добавить необходимые папки для исключения
