version: '3.10'

volumes:
  database:
  static:
  media:

services:
  database:
    container_name: hrspace_database
    image: postgres:alpine
    restart: always
    env_file:
    - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - database:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    container_name: hrspace_migrations
    restart: on-failure
    image: pandenic/hrspace_migrations
    env_file: .env
    depends_on:
      database:
        condition: service_healthy

  backend:
    container_name: hrspace_backend
    restart: always
    image: pandenic/hrspace_backend
    volumes:
      - media:/app/media/
    env_file: .env
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: hrspace_frontend
    restart: always
    image: asbest/hrspace-frontend
    volumes:
      - static:/app/result_build

  gateway:
    container_name: hrspace_gateway
    restart: always
    image: pandenic/hrspace_gateway
    volumes:
      - static:/usr/share/nginx/html/staticfiles/
      - media:/usr/share/nginx/html/media/
    ports:
      - "8000:80"
    links:
      - backend
    depends_on:
      - backend
