version: "3.10"

volumes:
  postgres:

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_hrspace
    restart: always
    env_file:
    - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data/
