version: "3.10"

volumes:
  database:

services:
  database:
    image: postgres:alpine
    container_name: hrspace_database
    restart: always
    env_file:
    - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - database:/var/lib/postgresql/data/
